registry {
  type = "nacos"
  nacos {
    application = "seata-server"
    serverAddr = "127.0.0.1:8848"
    group = "SEATA_GROUP"
    namespace = "public"
    username = "nacos"
    password = "nacos"
  }
}

config {
  type = "file"
  file {
    name = "file.conf"
  }
}

